import React,{useState} from'react';
import{createRoot}from'react-dom/client';
import{Home,BookOpen,Heart,BarChart3,Tag,Settings,Search,MapPin,Bell,Plus,Store,CupSoda,ChevronRight,Check,RotateCcw,X,Navigation}from'lucide-react';
import'./styles.css';import'./styles-extra.css';
const shops=[
{id:1,name:'春水堂',branch:'台北中山店',area:'台北市',distance:350,color:'#b98556',drinks:[['珍珠奶茶',75,'🧋'],['鐵觀音拿鐵',80,'🥤'],['翡翠檸檬',70,'🍋']]},
{id:2,name:'五十嵐',branch:'板橋文化店',area:'新北市',distance:450,color:'#2d73b9',drinks:[['四季春青茶',40,'🍵'],['波霸奶茶',60,'🧋'],['檸檬綠',55,'🍋']]},
{id:3,name:'麻古茶坊',branch:'台中公益店',area:'台中市',distance:600,color:'#d94943',drinks:[['芝芝芒果果粒',95,'🥭'],['金萱雙Q',65,'🧋'],['翡翠柳橙',75,'🍊']]},
{id:4,name:'可不可熟成紅茶',branch:'台北林森店',area:'台北市',distance:750,color:'#173d56',drinks:[['熟成紅茶',40,'🍂'],['胭脂多多',60,'🥤'],['春芽冷露',45,'🌱']]}];
const sugars=['無糖','微糖','半糖','少糖','全糖'],ices=['去冰','微冰','少冰','正常冰','熱飲'],toppings=['珍珠','波霸','椰果','布丁','仙草','寒天'];
const seed=[{id:101,shop:'春水堂',drink:'珍珠奶茶',rating:4,sugar:'半糖',ice:'少冰',repurchase:'yes',date:'今天'},{id:102,shop:'五十嵐',drink:'鐵觀音拿鐵',rating:5,sugar:'微糖',ice:'少冰',repurchase:'yes',date:'昨天'},{id:103,shop:'麻古茶坊',drink:'翡翠檸檬',rating:3.5,sugar:'半糖',ice:'微冰',repurchase:'maybe',date:'2 天前'}];
const nav=[[Home,'首頁'],[BookOpen,'品飲日記'],[Store,'收藏店家'],[Heart,'我的最愛'],[BarChart3,'統計總覽'],[Tag,'標籤管理']];
function App(){
 const[page,setPage]=useState('首頁'),[shopQ,setShopQ]=useState(''),[drinkQ,setDrinkQ]=useState(''),[area,setArea]=useState('全部地區'),[areaOpen,setAreaOpen]=useState(false),[nearby,setNearby]=useState(false),[notice,setNotice]=useState(false),[unread,setUnread]=useState(true);
 const[shop,setShop]=useState(shops[0]),[drink,setDrink]=useState(shops[0].drinks[0]),[sugar,setSugar]=useState('半糖'),[ice,setIce]=useState('少冰'),[tops,setTops]=useState(['珍珠']),[rating,setRating]=useState(4),[note,setNote]=useState('茶香很順口，珍珠軟硬剛好。'),[again,setAgain]=useState('yes'),[saved,setSaved]=useState(false);
 const[records,setRecords]=useState(()=>{try{return JSON.parse(localStorage.getItem('siplog-records'))||seed}catch{return seed}});
 let filtered=shops.filter(s=>(area==='全部地區'||s.area===area)&&(s.name+s.branch+s.area).toLowerCase().includes(shopQ.trim().toLowerCase()));if(nearby)filtered=[...filtered].sort((a,b)=>a.distance-b.distance);
 const drinks=shop.drinks.filter(d=>d[0].includes(drinkQ.trim())),avg=records.length?(records.reduce((a,r)=>a+r.rating,0)/records.length).toFixed(1):'0.0';
 const go=p=>{setPage(p);setNotice(false);window.scrollTo({top:0,behavior:'smooth'})},pick=s=>{setShop(s);setDrink(s.drinks[0]);setDrinkQ('')},toggle=t=>setTops(v=>v.includes(t)?v.filter(x=>x!==t):v.length<3?[...v,t]:v);
 const save=()=>{let r={id:Date.now(),shop:shop.name,drink:drink[0],rating,sugar,ice,toppings:tops,note,repurchase:again,date:'剛剛'},next=[r,...records];setRecords(next);localStorage.setItem('siplog-records',JSON.stringify(next));setSaved(true);setUnread(true);setTimeout(()=>setSaved(false),1800)};
 return <div className="app"><aside><div className="brand"><span>🧋</span><b>SipLog</b><small>喝飲誌</small></div><nav>{nav.map(([I,t])=><button onClick={()=>go(t)} className={page===t?'active':''} key={t}><I size={19}/>{t}</button>)}</nav><div className="asideBottom"><button onClick={()=>go('設定')} className={page==='設定'?'active':''}><Settings size={19}/>設定</button><div className="profile"><span>小</span><div><b>小茶日常</b><small>熱愛每一杯好茶</small></div></div></div></aside>
 <main><header><div><p className="eyebrow">PERSONAL DRINK JOURNAL</p><h1>{page==='首頁'?'今天想喝什麼？ 🧋':page}</h1><p>{page==='首頁'?'記錄每一杯，找到你的命定飲料。':'你的 SipLog 個人品飲空間'}</p></div><div className="headActions"><div className="noticeWrap"><button aria-label="通知" className="icon" onClick={()=>{setNotice(v=>!v);setUnread(false)}}><Bell size={20}/>{unread&&<i/>}</button>{notice&&<Notice close={()=>setNotice(false)} count={records.length}/>}</div><button className="primary" onClick={()=>go('首頁')}><Plus size={18}/>快速記錄</button></div></header>
 {page==='首頁'?<section className="builder"><div className="steps">{['搜尋店家','選擇飲料','甜度與冰量','評分與備註'].map((x,i)=><div className="step" key={x}><span>{i+1}</span><b>{x}</b>{i<3&&<em/>}</div>)}</div><div className="columns">
 <div className="panel"><div className="panelTitle"><span><Store size={17}/>搜尋店家</span><small>{filtered.length} 間店家</small></div><label className="search"><Search size={17}/><input aria-label="搜尋店家" value={shopQ} onChange={e=>setShopQ(e.target.value)} placeholder="輸入店名、分店或城市"/>{shopQ&&<button onClick={()=>setShopQ('')}><X size={14}/></button>}</label><div className="chips"><button className={nearby?'on':''} onClick={()=>setNearby(v=>!v)}><Navigation size={14}/>{nearby?'已依距離排序':'附近店家'}</button><div className="locationPicker"><button onClick={()=>setAreaOpen(v=>!v)}><MapPin size={14}/>{area}⌄</button>{areaOpen&&<div className="areaMenu">{['全部地區','台北市','新北市','台中市'].map(a=><button onClick={()=>{setArea(a);setAreaOpen(false)}} key={a}>{a}{area===a&&<Check size={13}/>}</button>)}</div>}</div></div><div className="shopList">{filtered.length?filtered.map(s=><button onClick={()=>pick(s)} className={shop.id===s.id?'selected':''} key={s.id}><i style={{background:s.color}}>{s.name[0]}</i><div><b>{s.name} · {s.branch}</b><small>{s.area} · 距離 {s.distance} 公尺</small></div>{shop.id===s.id&&<Check size={16}/>}</button>):<Empty text="找不到符合的店家"/>}</div></div>
 <div className="panel"><div className="panelTitle"><span><CupSoda size={17}/>選擇飲料</span><small>{shop.name}</small></div><label className="search"><Search size={17}/><input aria-label="搜尋飲料" value={drinkQ} onChange={e=>setDrinkQ(e.target.value)} placeholder="搜尋飲料名稱"/>{drinkQ&&<button onClick={()=>setDrinkQ('')}><X size={14}/></button>}</label><div className="drinkList">{drinks.length?drinks.map(d=><button onClick={()=>setDrink(d)} className={drink[0]===d[0]?'selected':''} key={d[0]}><span className="drinkEmoji">{d[2]}</span><div><b>{d[0]}</b><small>NT$ {d[1]}</small></div>{drink[0]===d[0]&&<Check size={16}/>}</button>):<Empty text="找不到這杯飲料"/>}</div></div>
 <div className="panel"><div className="panelTitle"><span>客製這一杯</span><small>最多 3 種配料</small></div><Option title="甜度" items={sugars} value={sugar} set={setSugar}/><Option title="冰量" items={ices} value={ice} set={setIce}/><Option title="加料" items={toppings} value={tops} set={toggle} multi/></div></div>
 <div className="review"><div><p className="eyebrow">YOUR RATING</p><h2>這杯值得幾顆星？</h2><div className="stars">{[1,2,3,4,5].map(n=><button onClick={()=>setRating(n)} className={n<=rating?'on':''} key={n}>★</button>)}<b>{rating}.0</b></div></div><label className="note"><span>備註 <small>（選填）</small></span><textarea maxLength="200" value={note} onChange={e=>setNote(e.target.value)}/><small>{note.length} / 200</small></label><div className="again"><span>下次還會點？</span><div>{[['yes','♥ 會！很喜歡'],['maybe','☺ 可能會'],['no','○ 不會']].map(([v,t])=><button className={again===v?'on':''} onClick={()=>setAgain(v)} key={v}>{t}</button>)}</div><button className="save" onClick={save}>{saved?<><Check size={18}/>已儲存！</>:<><CupSoda size={18}/>儲存這杯</>}</button></div></div></section>:<Page name={page} records={records} shops={shops} avg={avg} home={()=>go('首頁')}/>}</main>
 <Right records={records} avg={avg} go={go} setRecords={setRecords}/></div>}
function Page({name,records,shops,avg,home}){let data=name==='收藏店家'?shops.map(s=>[s.id,s.name,s.branch]):name==='我的最愛'?records.filter(r=>r.repurchase==='yes').map(r=>[r.id,r.drink,r.shop]):records.map(r=>[r.id,r.drink,r.shop]);return <section className="contentPage"><div className="contentPageHead"><h2>{name}</h2><button onClick={home}><Plus size={16}/>新增品飲紀錄</button></div>{name==='統計總覽'?<div className="bigStats"><article><b>{records.length}</b><small>品飲總數</small></article><article><b>{avg}</b><small>平均評分</small></article></div>:name==='設定'?<div className="settingsList"><label>資料儲存 <small>保存在此瀏覽器</small></label><label>介面語言 <small>繁體中文</small></label></div>:name==='標籤管理'?<div className="tagCloud">{[...new Set(records.flatMap(r=>[r.sugar,r.ice,...(r.toppings||[])]))].map(x=><span key={x}># {x}</span>)}</div>:<div className="pageList">{data.map(x=><article key={x[0]}><span>🧋</span><div><b>{x[1]}</b><small>{x[2]}</small></div></article>)}</div>}</section>}
function Notice({close,count}){return <div className="notificationPanel"><div><b>通知</b><button onClick={close}><X size={16}/></button></div><article><span>✓</span><p><b>品飲紀錄已同步</b><small>目前共有 {count} 杯飲料紀錄</small></p></article><article><span>★</span><p><b>本週品飲回顧</b><small>別忘了為最近喝過的飲料評分</small></p></article><button className="markRead" onClick={close}>全部標示為已讀</button></div>}
function Right({records,avg,go,setRecords}){return <section className="right"><div className="rightHead"><div><p className="eyebrow">TASTING LOG</p><h2>近期品飲</h2></div><button onClick={()=>go('品飲日記')}>查看全部 <ChevronRight size={15}/></button></div><div className="recent">{records.slice(0,4).map(r=><article key={r.id}><span className="miniCup">🧋</span><div><b>{r.drink}</b><small>{r.shop} · {r.sugar} / {r.ice}</small><span className="miniStars">{'★'.repeat(Math.round(r.rating))}<em>{r.rating}</em></span></div><time>{r.date}</time></article>)}</div><div className="summary"><p className="eyebrow">RATING OVERVIEW</p><div><strong>{avg}</strong><span><b>平均評分</b><small>{records.length} 杯品飲紀錄</small></span></div><div className="bar"><i style={{width:`${+avg/5*100}%`}}/></div></div><div className="stats"><div><CupSoda/><b>{records.length}</b><small>品飲總數</small></div><div><Heart/><b>{records.filter(x=>x.repurchase==='yes').length}</b><small>願意再點</small></div></div><button className="reset" onClick={()=>{localStorage.removeItem('siplog-records');setRecords(seed)}}><RotateCcw size={14}/>重設示範資料</button></section>}
function Option({title,items,value,set,multi}){return <div className="option"><b>{title}</b><div className="optionGrid">{items.map(x=><button className={(multi?value.includes(x):value===x)?'on':''} onClick={()=>set(x)} key={x}>{x}</button>)}</div></div>};function Empty({text}){return <div className="empty"><Search size={20}/><b>{text}</b><small>換個關鍵字或地區試試看</small></div>};createRoot(document.getElementById('root')).render(<App/>);
